### ISSUE TITLE
Return type `Task` is not allowed

### ISSUE THREAD

**Issue by markusschaber** [tmds/Tmds.ExecFunction#19]
Hi, the readme claims: _The function can have the same signature of a .NET Main: a `void`/`string[]` argument, and a` void`/`int`/`Task`/`Task<int>` return type._

However, the Method `ConfigureProcessStartInfoForMethodInvocation()` only allows `void`, `int` and `Task<int>`:
https://github.com/tmds/Tmds.ExecFunction/blob/main/src/Tmds.ExecFunction/ExecFunction.cs#L148

Is this a known bug? Is the fix as easy as extending the check, or is more work required?

**Comment by markusschaber** [comment]
Info: This issue has low priority. It seems I cannot use Tmds.ExecFunction anyways, as it doesn't work with the Test runner used by JetBrains Rider / Resharper.

**Comment by tmds** [comment]
This is part of 0.7.0 which was just published to nuget.org.
