### ISSUE TITLE
Expose method that returns the process StartInfo without executing it

### ISSUE THREAD

**Issue by davidfowl** [tmds/Tmds.ExecFunction#23]
It would allow for deferring the execution or delegating it to another process (orchestrator)

**Comment by tmds** [comment]
> It would allow for deferring the execution or delegating it to another process (orchestrator)

A question to understand the use-case better. To delegate to another process, will you be serializing the `ProcessStartInfo`?

How does the following API look? Will it enable your use-cases?

```cs
public static class ExecFunction
{
ProcessStartInfo GetProcessStartInfo(Action action);
ProcessStartInfo GetProcessStartInfo(Action<string[]> action, string[] args);
ProcessStartInfo GetProcessStartInfo(Func<int> action);
ProcessStartInfo GetProcessStartInfo(Func<string[], int> action, string[] args);
ProcessStartInfo GetProcessStartInfo(Func<Task> action);
ProcessStartInfo GetProcessStartInfo(Func<string[], Task> action, string[] args);
ProcessStartInfo GetProcessStartInfo(Func<Task<int>> action);
ProcessStartInfo GetProcessStartInfo(Func<string[], Task<int>> action, string[] args);
```

**Comment by tmds** [comment]
ok. If you want, you can make a PR that adds the above API. And otherwise, I'll make some time for it this week.
It should be doable to have this on nuget.org by Friday.
