### ISSUE TITLE
Process recursion core 3 and netstandard2.0

### ISSUE THREAD

**Issue by Arsenal83** [tmds/Tmds.ExecFunction#4]
Hey.
I decided to try this package in the core 3 application, netstandard2.0.
and here is the result

![image](https://user-images.githubusercontent.com/26539477/71011086-de808200-20fd-11ea-84bc-76e484bf9ea9.png)

![image](https://user-images.githubusercontent.com/26539477/71011001-bf81f000-20fd-11ea-8cae-2698c312bb83.png)

**Comment by tmds** [comment]
nice process recursion :smile: 

Have a look in the README, it tells you what to do.
