### ISSUE TITLE
Support mac

### ISSUE THREAD

**Issue by tmds** [tmds/Tmds.ExecFunction#6]
This package doesn't support mac.

The implementation we need is something similar to: https://github.com/PowerShell/PowerShell/blob/14960b57728cb4210fe6262dc51c1b88e85daa74/src/powershell/Program.cs#L124.

cc @MarcoRossignoli

**Comment by nickvdyck** [comment]
I quickly hacked something together this evening and managed to get the tests passing. Will clean up my code tomorrow and make a PR if that's ok for you 😄 .

<img width="1241" alt="Screenshot 2020-03-21 at 23 56 58" src="https://user-images.githubusercontent.com/6469315/77238381-b6f2f700-6bcf-11ea-8b82-67fe56708d3d.png">

**Comment by MarcoRossignoli** [comment]
Thanks a lot!
