### ISSUE TITLE
Assembly signature

### ISSUE THREAD

**Issue by MarcoRossignoli** [tmds/Tmds.ExecFunction#9]
We treat warning as error and we get exception during build because lib is not signed, I think should be signed.
```
CSC : error CS8002: Referenced assembly 'Tmds.ExecFunction, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [C:\git\coverlet\test\coverlet.core.tests\coverlet.core.tests.csproj]
```

For now we hide with
```
<NoWarn>$(NoWarn);CS8002</NoWarn>
```

**Comment by tmds** [comment]
@MarcoRossignoli I'm happy to accept a PR here. Generating the key for signing is a unfortunately a pain for us using .NET Core on Linux only.
